### ISSUE TITLE
error with no hup

### ISSUE THREAD

**Issue by CuongNN218** [Shreeshrii/tesstrain-sanPlusMinus#1]
Hi, Thanks for your great work. I try to reproduce your result but i got some errors. 
![image](https://user-images.githubusercontent.com/26113323/113109770-80af7500-9230-11eb-84c5-52d088c26472.png)
Can you help me ? @Shreeshrii

**Comment by sanskrit-documents-ocr** [comment]
```
nohup make training MODEL_NAME=${MODEL_NAME} START_MODEL=san TESSDATA=data MAX_ITERATIONS=9999999  LANG_TYPE=Indic  DEBUG_INTERVAL=-1  > plot/${MODEL_NAME}.LOG &
```

If you use the above command, it will start the Makefile and create a log file in plot/${MODEL_NAME}.LOG 

For details on nohup, see https://linux.die.net/man/1/nohup
